# Generated by Django 4.2.1 on 2023-05-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsystem', '0003_remove_actuator_unique_name_remove_actuator_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActuatorLog',
        ),
    ]
