# Generated by Django 4.2.1 on 2023-05-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsystem', '0004_delete_actuatorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='subsystem.actuator')),
            ],
        ),
    ]
